### ISSUE TITLE
Can you bind the AccordionView?

### ISSUE THREAD

**Issue by rdollarhide** [DottorPagliaccius/Xamarin-Custom-Controls#3]
Is it possible to bind the AccordionView so that AccordionViewItems can be added programmatically from a ViewModel using Xamarin Forms?  If so, do you have any examples of this?

**Comment by DottorPagliaccius** [comment]
Uhm... do you mean adding AccordionViewItems by code instead of XAML? Of course you can, just add the AccordionViewItem to the AccordionView Children collection. Unfortunately I'm a pure-XAML guy, so I've no sample code right now, but it should be very simple.

**Comment by rdollarhide** [comment]
I was actually hoping for an example directly related to a ViewModel.  I guess I'll just dive into it and try to figure out the bindings.

**Comment by DottorPagliaccius** [comment]
OK, now I got it. No, there's no way to do that from the ViewModel, because you can't directly reference UI stuff from there. Also there is no way, as far as I now, to bind an observable collection of controls to the children collection of a StackLayout (AccordionView is basically an extended StackLayout).

This control is useful if you have static heterogeneous contents for each item of the Accordion; I'm planning to deliver another version of the Accordion with a bindable ItemSource property and a single ItemTemplate (basically a Repeater of templated AccordionViewItem), but for now is a TODO.

**Comment by rdollarhide** [comment]
Thanks for the thorough response.  I have used the AccordionView in static settings which has been great.  Thanks for your efforts.  I look forward to the enhancements.

**Comment by DottorPagliaccius** [comment]
@rdollarhide I've uploaded a new versione of the control, a bindable Accordion (AccordionRepeaterView).
