### ISSUE TITLE
Re Positioning Issue

### ISSUE THREAD

**Issue by lijusparkt** [DottorPagliaccius/Xamarin-Custom-Controls#38]
After choose an item in Repeater view, I have saved it into my Database. When i came back to the page i can't able scroll to that position automatically..

ie, I can able to highlight the previous selected item. but user need to scroll to that position ; to view that. (scroll to position is not possible).

**Comment by DottorPagliaccius** [comment]
Hi, this control is not meant to be used like a listview, so it makes no sense to implement a scrollToPosition.

The problem is that you replace all items in ItemSource, after update the selected element on the DB: try refreshing only that element and not the entire list, or use the ScrollToPosition of the parent ScrollView.

**Comment by lijusparkt** [comment]
Hi @DottorPagliaccius , First i'm setting item source and then  executing SelectedItemCommand.Execute(item). I'm not replacing item source after executing "SelectedItemCommand".   
Item selection is working fne

**Comment by DottorPagliaccius** [comment]
It should not reset position, what are you doing in SelectedItemCommand? Navigate to another page? There is code in On Appearing?

**Comment by lijusparkt** [comment]
Hi,
In repeater view i'm selecting an item; then i'm saving current item in my
database . After that i'm navigating to another pages , and also user can
go back to previous pages.
I'm saving these datas like a draft. If user again open(new page) this page
i want to repopulate the values . i have the selected item and its index.
and i also can highlight the selected item; if the previous selected item
is in the last one; Repeater view is not automatically scroll to that that
position .
This is the problem that i'm facing.   I'm Using MVVM method

**Comment by DottorPagliaccius** [comment]
So you re-populate the list after navigation, this is the reason why the position is being reset; after you refresh the list you can use the lastIndex and the ScrollToPosition of the parent ScrollView calculating the Y value (=RowHeight X lastClickendElementIndex).

Since this is strictly a UI thing, you can't do in ViewModel, you must do in page code.

**Comment by lijusparkt** [comment]
Ok, Thanks for your support  Brother;😊

**Comment by lijusparkt** [comment]
Hi,
Like Listview; Is it possible to add Header or Footer in Repeater view.

**Comment by DottorPagliaccius** [comment]
I removed that option, I think it was not the case because the control is not meant to be used like a ListView, if you need ad Header/Footer, just put a StackLayout before or after the repeater.

**Comment by lijusparkt** [comment]
Ok;🙂
